package beetrap.btfmc.render.entity.model;

import beetrap.btfmc.render.entity.state.FlowerEntityRenderState;
import net.minecraft.client.model.ModelData;
import net.minecraft.client.model.ModelPart;
import net.minecraft.client.model.ModelPartBuilder;
import net.minecraft.client.model.ModelPartData;
import net.minecraft.client.model.ModelTransform;
import net.minecraft.client.model.TexturedModelData;
import net.minecraft.client.render.entity.model.EntityModel;
import net.minecraft.client.render.entity.model.EntityModelPartNames;

public class FlowerEntityModel extends
        EntityModel<FlowerEntityRenderState> {
    private final ModelPart base;

    public FlowerEntityModel(ModelPart root) {
        super(root);
        this.base = root.getChild(EntityModelPartNames.CUBE);
    }

    // could be generated by BlockBench
    public static TexturedModelData getTexturedModelData() {
        ModelData modelData = new ModelData();
        ModelPartData modelPartData = modelData.getRoot();
        modelPartData.addChild(EntityModelPartNames.CUBE, ModelPartBuilder.create().uv(0, 0).cuboid(-6F, 12F, -6F, 12F, 12F, 12F), ModelTransform.pivot(0F, 0F, 0F));
        return TexturedModelData.of(modelData, 64, 64);
    }

    @Override
    public void setAngles(FlowerEntityRenderState state) {
        super.setAngles(state);
    }
}
